services:
  - type: web
    name: faceforger-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
